version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt_packages:
    - gdal-bin
    - python3-gdal
    - libgdal-dev
    - python3-dev
    - libpq-dev
    - build-essential
  jobs:
      post_create_environment:
       - pip install --upgrade pip
       - pip install wheel
       - pip install numpy
       - pip install setuptools==57.5.0
       - pip install gdal==3.0.4

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements-dev.txt
  system_packages: true  
